export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const LOADING = 'LOADING'
export const ERROR = 'ERROR'
//filter
export const LOAD_MAX_PRICE = 'LOAD_MAX_PRICE'
export const RESET_ALL_FILTER = 'RESET_ALL_FILTER'
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY'
export const FILTER_BY_BRANDS = 'FILTER_BY_BRANDS'
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE'
export const FILTER_BY_RATING = 'FILTER_BY_RATING'
export const SORT_BY = 'SORT_BY'
//category
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
//wishlist
export const GET_ALL_WISHLIST_PRODUCTS = 'GET_ALL_WISHLIST_PRODUCTS'
export const ADD_WISHLIST_PRODUCT = 'ADD_WISHLIST_PRODUCT'
export const UPDATE_WISHLIST_PRODUCT = 'UPDATE_WISHLIST_PRODUCT'
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST'
// cart
export const GET_ALL_CART_PRODUCTS = 'GET_ALL_CART_PRODUCTS'
export const ADD_CART_PRODUCT = 'ADD_CART_PRODUCT'
export const UPDATE_CART_PRODUCT = 'UPDATE_CART_PRODUCT'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
