export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const LOADING = 'LOADING'
export const ERROR = 'ERROR'
//filter
export const LOAD_MAX_PRICE = 'LOAD_MAX_PRICE'
export const RESET_ALL_FILTER = 'RESET_ALL_FILTER'
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY'
export const FILTER_BY_BRANDS = 'FILTER_BY_BRANDS'
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE'
export const FILTER_BY_RATING = 'FILTER_BY_RATING'
export const SORT_BY = 'SORT_BY'
//category
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
//wishlist
export const GET_WISHLIST = 'GET_WISHLIST'
export const ADD_WISHLIST_PRODUCT = 'ADD_WISHLIST_PRODUCT'
export const UPDATE_WISHLIST_PRODUCT = 'UPDATE_WISHLIST_PRODUCT'
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST'
export const RESET_WISHLIST = 'RESET_WISHLIST'
// cart
export const GET_CART = 'GET_CART'
export const ADD_CART_PRODUCT = 'ADD_CART_PRODUCT'
export const UPDATE_CART_PRODUCT = 'UPDATE_CART_PRODUCT'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const INCREMENT_DECREMENT__QUANTITY = 'INCREMENT_DECREMENT__QUANTITY'
export const EMPTY_CART = 'EMPTY_CART'
export const RESET_CART = 'RESET_CART'
//THEME
export const DARK_MODE = 'DARK_MODE'
export const LIGHT_MODE = 'LIGHT_MODE'
// auth
export const SAVE_USER_INFO = 'SAVE_USER_INFO'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOG_OUT = 'LOG_OUT'
//user 
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const ADD_ADDRESS = 'ADD_ADDRESS'
export const DELETE_ADDRESS = 'DELETE_ADDRESS'
export const GET_ADDRESS = 'GET_ADDRESS'
export const DEFAULT_ADDRESS = 'DEFAULT_ADDRESS'
//order
export const ADD_ORDER = 'ADD_ORDER'
export const GET_ORDER = 'GET_ADDRESS'
